FROM apache/airflow:2.8.1

USER root

RUN apt-get update && \
    apt-get install -y default-jdk-headless procps && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/default-java
ENV PATH=$PATH:$JAVA_HOME/bin

USER airflow